services:
  postgres:
    image: postgres:15
    container_name: gemini_flow_db2
    environment:
      POSTGRES_DB: gemini_flow
      POSTGRES_USER: GeminiFlow
      POSTGRES_PASSWORD: LinarikEmilkaRianka
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gemini_flow"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: gemini_flow_redis2
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: gemini_flow_bot2
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=postgresql://GeminiFlow:postgres@LinarikEmilkaRianka:5432/gemini_flow
      - REDIS_URL=redis://redis:6379
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - ADMIN_IDS=${ADMIN_IDS}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["python", "main.py"]
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
    driver: local