"""Fix User-Referral relationships and rename Settings to Setting

Revision ID: 18cf7711878e
Revises: 1a6c8d8c3dab
Create Date: 2025-08-05 17:01:34.667257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18cf7711878e'
down_revision: Union[str, None] = '1a6c8d8c3dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
