"""Add ForeignKey user_id to messages table

Revision ID: 1a6c8d8c3dab
Revises: 1c37c515cab9
Create Date: 2025-08-05 16:51:48.273835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6c8d8c3dab'
down_revision: Union[str, None] = '1c37c515cab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'model_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'gemini-1.5-flash'::character varying"))
    op.add_column('messages', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'user_id')
    op.alter_column('chats', 'model_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'gemini-1.5-flash'::character varying"))
    # ### end Alembic commands ###
