"""Fix model_name column: add default and allow null temporarily

Revision ID: 1c37c515cab9
Revises: a5c9335977d2
Create Date: 2025-08-05 16:48:24.484322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c37c515cab9'
down_revision: Union[str, None] = 'a5c9335977d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Разрешить NULL временно (если столбец NOT NULL)
    op.alter_column('chats', 'model_name', nullable=True)
    # 2. Установить DEFAULT значение
    op.alter_column('chats', 'model_name', server_default=sa.text("'gemini-1.5-flash'::character varying"))
    # 3. Заполнить существующие NULL значения дефолтным значением
    op.execute("UPDATE chats SET model_name = 'gemini-1.5-flash' WHERE model_name IS NULL")
    # 4. Снова сделать NOT NULL (если нужно)
    op.alter_column('chats', 'model_name', nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Снова разрешить NULL (если было NOT NULL)
    op.alter_column('chats', 'model_name', nullable=True)
    # 2. Убрать DEFAULT значение
    op.alter_column('chats', 'model_name', server_default=None)
    # 3. Опционально: очистить значения, если нужно вернуть к состоянию NULL (или оставить как есть)
    # op.execute("UPDATE chats SET model_name = NULL") # Обычно не делается в downgrade
    # 4. Снова сделать NOT NULL, если было изначально (или оставить nullable=True)
    # op.alter_column('chats', 'model_name', nullable=False) # Только если изначально было NOT NULL
    # ### end Alembic commands ###