"""Add ForeignKey user_id to messages table

Revision ID: 4f54ce379a79
Revises: 2b7a0364d796
Create Date: 2025-08-05 17:13:49.834463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f54ce379a79'
down_revision: Union[str, None] = '2b7a0364d796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('messages', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('messages', 'chat_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'chat_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('messages', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'tokens_used')
    # ### end Alembic commands ###
