"""Add chat settings fields and ensure all tables exist

Revision ID: a5c9335977d2
Revises: 
Create Date: 2025-08-05 16:38:38.629610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c9335977d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('chats', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('chats', sa.Column('top_p', sa.Float(), nullable=True))
    op.add_column('chats', sa.Column('top_k', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('system_prompt', sa.Text(), nullable=True))
    op.alter_column('chats', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chats', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('chats', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('chats', 'system_prompt')
    op.drop_column('chats', 'top_k')
    op.drop_column('chats', 'top_p')
    op.drop_column('chats', 'temperature')
    op.drop_column('chats', 'is_active')
    # ### end Alembic commands ###
